version: 2
jobs:
  build:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: v2-gradle-{{ checksum "build.gradle.kts" }}

      - run:
          name: Run tests
          command: ./gradlew --build-cache check

      - run:
          name: Build frontend
          command: ./gradlew --build-cache jsBrowserProductionWebpack

      - add_ssh_keys:
          fingerprints:
            - b2:01:83:8d:4e:e6:72:11:5f:57:70:11:ec:57:29:42

      # CircleCI workflow configuration is a disaster, so do branch check manually
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deploy.sh
            else
              echo "Not deploying from '${CIRCLE_BRANCH}' branch"
            fi

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-gradle-{{ checksum "build.gradle.kts" }}

      - store_test_results:
          path: build/test-results/jvmTest

      - store_artifacts:
          path: build/test-results/jvmTest
          when: always
