version: 2

jobs:
  test_backend:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run:
          name: Create service key
          command: |
            KEY_FILE="${HOME}/service-key.json"
            echo "${GCLOUD_SERVICE_KEY}" > "${KEY_FILE}"
            echo "export GOOGLE_APPLICATION_CREDENTIALS=${KEY_FILE}" >> "${BASH_ENV}"
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - v1-gradle-{{ .Branch }}-
            - v1-gradle-
      - run:
          name: Run tests
          command: ./gradlew check
      - run:
          name: Run scraper application
          command: ./gradlew run
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

  build_frontend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-
      - run:
          name: Install dependencies
          command: cd frontend && yarn install
      - run:
          name: Lint
          command: cd frontend && yarn lint
      - run:
          name: Build
          command: cd frontend && yarn build
      - save_cache:
          paths:
            - frontend/build
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - b2:01:83:8d:4e:e6:72:11:5f:57:70:11:ec:57:29:42
      - run:
          name: Deploy
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_backend
      - build_frontend
      - deploy:
          requires:
            - build_frontend
          filters:
            branches:
              only: master
