version: 2
jobs:
  build:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Run tests
          command: ./gradlew check

      - run:
          name: Build frontend
          command: ./gradlew jsBrowserProductionWebpack

      # TODO - only on master

      - add_ssh_keys:
          fingerprints:
            - b2:01:83:8d:4e:e6:72:11:5f:57:70:11:ec:57:29:42

      - run:
          name: Deploy
          command: ./scripts/deploy.sh

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - store_test_results:
          path: build/test-results/jvmTest

      - store_artifacts:
          path: build/test-results/jvmTest
          when: always
