version: 2

jobs:
  test_backend:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - v1-gradle-{{ .Branch }}-
            - v1-gradle-
      - run:
          name: Run tests
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

  build_frontend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-
      - run:
          name: Install dependencies
          command: cd frontend && yarn install
      - run:
          name: Build frontend
          command: cd frontend && yarn build
      - save_cache:
          paths:
            - frontend/build
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - b2:01:83:8d:4e:e6:72:11:5f:57:70:11:ec:57:29:42
      - run:
          name: Deploy
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_backend:
          filters:
            branches:
              ignore: master
      - build_frontend
      - deploy:
          requires:
            - build_frontend
          filters:
            branches:
              only: master
