name: Build
on: [push]

# TODO - Gradle cache
# TODO - job for Run scraper
# TODO - ensure new commit cancels active runs

jobs:

  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 13.0.1

      - name: Create file for service key
        run: echo "${GCLOUD_SERVICE_KEY}" > "${GITHUB_WORKSPACE}/service-key.json"
        shell: bash
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: v1-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run tests
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="${GITHUB_WORKSPACE}/service-key.json"
          ./gradlew --no-daemon check

      - name: Capture test results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/test-results/test
