name: Build
on: [push]

# TODO - Gradle cache
# TODO - job for Run scraper
# TODO - test results / logs
# TODO - ensure new commit cancels active runs


jobs:

  test_backend:
    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${GITHUB_WORKSPACE}/service-key.json

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 13.0.1

      - name: Create file for service key
        run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
        shell: bash

      - name: Run tests
        run: ./gradlew check

